
# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: nixfmt-rfc-style
        name: Format Nix files with RFC-style nixfmt
        entry: nixfmt  # <-- use nixfmt because nixfmt-rfc-style provides the binary as 'nixfmt'
        language: system
        files: \.nix$

