
# 🚀 Build & Cache: Runs on push to main, builds, and pushes to Cachix

name: 🚀 Build & Cache

on:
  push:
    branches:
      - main

jobs:
  build-and-cache:
    name: 📦 Build & Push to Cachix
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Nix + enable flakes
      - name: 🧊 Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      # 3️⃣ Setup Cachix with push permissions
      - name: 📦 Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: schrovimger
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # 4️⃣ (Optional but safe) Verify repo clean
      - name: 📁 Verify no uncommitted changes
        run: |
          git diff --exit-code

      # 5️⃣ (Optional but safe) Run flake checks again
      - name: 🔍 Run flake checks
        run: nix flake check --all-systems --no-update-lock-file

      # 6️⃣ Build default flake output
      - name: 🔨 Build default package
        run: nix build

      # 7️⃣ Push closure to Cachix
      - name: 🚀 Push to Cachix
        run: |
          echo "Pushing flake output closure to Cachix..."
          nix path-info --recursive .#default | cachix push schrovimger
