
# 🚀 Build and push full closure to Cachix on push to main
name: 🚀 Build & Cache

on:
  push:
    branches:
      - main

jobs:
  build-and-cache:
    name: 📦 Build & Push to Cachix
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Nix (pin version & enable flakes)
      - name: 🧊 Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      # 3️⃣ Setup Cachix with push access
      - name: 📦 Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: schrovimger
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # 4️⃣ Build default flake output (compile everything)
      - name: 🔨 Build default package
        run: nix build

      # 5️⃣ Push entire closure to Cachix (CORRECT)
      - name: 🚀 Push to Cachix
        run: |
          echo "Pushing flake output closure to Cachix..."
          nix path-info --recursive .#default | cachix push schrovimger
